name: ts-node-cloud-builder
description: |
  A build container for Typescript/node.js projects, includes Yarn and Lerna, as well as tooling for Vue 2.
inputs:
  entrypoint:
    description: |
      The command to run, e.g. "yarn", "lerna". See README.md for details.
    required: true
    default: yarn
  args:
    description: |
      The arguments to pass to the command, e.g. [ "run", "build" ]. Must be a JSON-formatted string.
    required: true
runs:
  using: "docker"
  image: "action.Dockerfile"
  args:
    - ${{ inputs.entrypoint }}
    - ${{ join(fromJSON(inputs.args)) }}
