name: Build and push container image

on:
  # Run workflow manually
  workflow_dispatch: {}
  # Run workflow every Tuesday, 9:13 AM
  schedule:
    - cron: "13 9 * * 2"
  # Run workflow on push to master
  push:
    branches:
      - master
    paths:
      - .github/workflows/**
      - lerna-resolver/**
      - Dockerfile
      - entrypoint.sh

jobs:
  build-and-push:
    name: Build and push container image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        node-versions: ["12", "14", "16", "lts"]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log in to Github Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Get access to GCR: https://github.com/docker/login-action#google-container-registry-gcr
      - name: Log in to Google Container Registry (cyberscan2)
        uses: docker/login-action@v1.10.0
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR2_JSON_KEY }}

      # Build the base image (for use in Google Cloud Build)
      - name: Build and push image
        id: build
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          build-args: |
            NODE_VERSION=${{ matrix.node_version }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.node_version }}
            ghcr.io/${{ github.repository }}:${{ matrix.node_version }}-${{ github.sha }}
            gcr.io/cyberscan2/ts-node-cloud-builder:${{ matrix.node_version }}
            gcr.io/cyberscan2/ts-node-cloud-builder:${{ matrix.node_version }}-${{ github.sha }}

      # Special treatment for lts & latest, see README.md for details
      - if: matrix.node_version == "lts"
        name: 'Tag "lts" as "latest"'
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/${{ github.repository }}:${{ matrix.node_version }}-${{ github.sha }}
          dst: |
            ghcr.io/${{ github.repository }}:latest
            gcr.io/cyberscan2/ts-node-cloud-builder:latest

      #####################################################################################################################
      # The image is also tagged & pushed as gcr.io/cyberscanauth/ts-node-cloud-builder for backwards compat. This needs to
      # happen in an extra step because both GCP projects share the same registry hostname (gcr.io) and should probably be
      # removed eventually.
      #
      - name: Log in to Google Container Registry (cyberscanauth)
        uses: docker/login-action@v1.10.0
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR1_JSON_KEY }}
      #
      - name: Push image to Google Container Registry (cyberscanauth)
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/${{ github.repository }}:${{ matrix.node_version }}-${{ github.sha }}
          dst: |
            gcr.io/cyberscanauth/ts-node-cloud-builder:${{ matrix.node_version }}
            gcr.io/cyberscanauth/ts-node-cloud-builder:${{ matrix.node_version }}-${{ github.sha }}
      #
      - if: matrix.node_version == "lts"
        name: 'Tag "lts" as "latest" (cyberscanauth)'
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/${{ github.repository }}:${{ matrix.node_version }}-${{ github.sha }}
          dst: |
            gcr.io/cyberscan2/ts-node-cloud-builder:latest
      #
      #####################################################################################################################
